#pragma once

#include "ducky_pch.h"

#include "graphics\window.h"
#include "graphics\transform.h"
#include "graphics\texture2d.h"
#include "graphics\spriteSheet.h"
#include "graphics\textureCube.h"
#include "graphics\camera.h"
#include "graphics\buffer.h"
#include "graphics\input.h"
#include "graphics\light.h"
#include "graphics\material.h"
#include "graphics\mesh.h"
#include "graphics\shader.h"
#include "graphics\materials\simpleMaterial.h"
#include "graphics\materials\pbrMaterial.h"
#include "graphics\materials\terrainMaterial.h"
#include "graphics\layer\layer3d.h"
#include "graphics\layer\layer2d.h"

#include "core\scene.h"
#include "core\entity.h"
#include "core\game.h"
#include "core\audioObject.h"
#include "core\components\triggerComponent.h"
#include "core\components\transformComponent.h"
#include "core\components\spriteComponent.h"
#include "core\components\meshComponent.h"
#include "core\components\rigidBodyComponent.h"
#include "core\components\audioComponent.h"
#include "core\physics\physicsScene.h"
#include "core\physics\rigidBody.h"
#include "core\physics\physicsShape.h"
#include "core\physics\physicsTrigger.h"

#include "utils\stringUtils.h"
#include "utils\compresser.h"
#include "utils\debug.h"
#include "utils\imageUtils.h"

#include "io\xml.h"
#include "io\basicio.h"
#include "io\byteStream.h"
#include "io\fileio.h"
#include "io\fontio.h"
#include "io\imageio.h"
#include "io\modelio.h"
#include "io\terrainio.h"
#include "io\vfs.h"
#include "io\serializable.h"

#undef min
#undef max